In [17]:
import pandas as pd

# Import Libraries

# Load the dataset

In [18]:
df = pd.read_csv('./data/marketing_campaign.csv')
# Subset the columns we are interested in
df = df[['ID','Year_Birth', 'Education','Marital_Status','Income','Kidhome', 'Teenhome', 'Dt_Customer','Recency','NumStorePurchases', 'NumWebVisitsMonth']]

In [27]:
df.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5

In [4]:
df.dtypes

ID                     int64
Year_Birth             int64
Education             object
Marital_Status        object
Income               float64
Kidhome                int64
Teenhome               int64
Dt_Customer           object
Recency                int64
NumStorePurchases      int64
NumWebVisitsMonth      int64
dtype: object

In [6]:
df.shape

(2240, 11)

# Grouping Data

In [19]:
# Get average (mean) number of purchases based on number of kids at home
# We are grouping by "Kidhome" column, and aggregating by "NumStorePurchases" column
df.groupby('Kidhome')['NumStorePurchases'].mean()

Kidhome
0    7.217324
1    3.863181
2    3.437500
Name: NumStorePurchases, dtype: float64

## `pd_dataframe.groupby()` Function
`pd_dataframe.groupby()` will split the data into groups based on predefined criteria. You can also group by more than one column by providing the list of column names to `groupby`. The output of `groupby` is  `GroupBy` object. We can use the following methods on this object:
1. `group_by_object.indices`: Shows how the groups were split. Output is a dictionary, where keys are the group names and values are indices of each group
2. `group_by_object.ngroups` will show the number of groups
3. `group_by_object.get_group('group_name')` to select a single group

# Appending Data by Rows
We may have multiple datasets with similar structure, or sample of the same dataset and we may want to append them into a single dataset.
**When we append datasets, we stitch the datasets along the rows**. The rows typically increase while the columns remain the same. The datasets are allowed to have a different number of rows but typically should have the same number of columns to avoid errors after appending.

In [20]:
# concat() takes in a list of dataframes as an argument
# concat_data = pd.concat([dataframe1, dataframe2])

![rowconcat](img/rowconcat.jpg)

# Concatenating Data by Columns
concatenating stitches columns together to provide a single dataset. The datasets are allowed to have a different number of columns but typically **should have the same number of rows** to avoid errors after concatenating.

In [35]:
# axis=1 indicates we are concatenating by colunmns, default is axis=0 which is row concatenation
# concat_data1 = pd.concat(dataframe1, dataframe2, axis=1)

![colconcat](img/colconcat.jpg)

# Merging Data
**We need a common column (join key column) across datasets on which we can perform a merge**.  The columns do not need to have the same name; they only need to have matching values within the two datasets.
1. **Left Join**: retain all the rows in the left dataframe. Values in the right dataframe that do not match the values in the left dataframe are added as `NaN`
2. **Right Join**: We retain all the rows in the right dataframe. Values in the left dataframe that do not match the values in the right dataframe are added as `NaN`
3. **Inner Join**: Retain only the common values in both the left and right dataframes in the result, there are no `NaN` values in this case
4. **Outer Join**: We retain all the rows for the left and right dataframes. If the values do not match, `NaN` is added to the result.

In [21]:
df1 = pd.read_csv("data/marketing_campaign_merge1.csv")
df2 = pd.read_csv("data/marketing_campaign_merge2.csv")

In [25]:
df1.head(5)

     ID  Year_Birth   Education
0  5524        1957  Graduation
1  2174        1954  Graduation
2  4141        1965  Graduation
3  6182        1984  Graduation
4  5324        1981         PhD

In [26]:
df2.head(5)

     ID Marital_Status   Income
0  5524         Single  58138.0
1  2174         Single  46344.0
2  4141       Together  71613.0
3  6182       Together  26646.0
4  5324        Married  58293.0

In [27]:
# Perform merge on ID column
merged_df = pd.merge(df1,df2, on="ID")
merged_df.head(5)

     ID  Year_Birth   Education Marital_Status   Income
0  5524        1957  Graduation         Single  58138.0
1  2174        1954  Graduation         Single  46344.0
2  4141        1965  Graduation       Together  71613.0
3  6182        1984  Graduation       Together  26646.0
4  5324        1981         PhD        Married  58293.0

# Sorting Data

In [28]:
df.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5

In [31]:
# Sort based on NumStorePurchases in decsending order
sorted_df = df.sort_values('NumStorePurchases', ascending=False)
sorted_df.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
1187,9855,1952,PhD,Single,62000.0,0,1,25-08-2013,25,13,4
803,9930,1944,PhD,Single,82716.0,0,0,05-11-2013,8,13,2
1144,819,1945,Graduation,Widow,63285.0,0,0,05-11-2013,84,13,3
286,10983,1952,Graduation,Together,75278.0,0,0,29-01-2013,17,13,3
1150,1453,1943,PhD,Widow,57513.0,0,0,06-07-2013,59,13,6

# Categorizing Data
Categorizing means binning, bucketing, or cutting a dataset. **It involves grouping the numeric values in a dataset into smaller intervals called bins or buckets**. When we bin numerical values, each bin becomes a categorical value.

In [33]:
df.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5

In [35]:
# Categorize the number of store purchases into high, moderate, and low categories
# Our bins can be interpreted as 0–4 (low), 5–8 (moderate), and 9–13 (high).
df['bins'] = pd.cut(x=df['NumStorePurchases'], bins=[0,4,8,13],labels=['Low','Moderate','High'])
df[['NumStorePurchases','bins']].head(5)

   NumStorePurchases      bins
0                  4       Low
1                  2       Low
2                 10      High
3                  4       Low
4                  6  Moderate

# Removing Duplicates

To the `drop_duplicates()` method, we supply the list of the subset columns as the first argument, we can drop all rows that contain duplicates based on those subset columns. This is useful when we have several columns and only a few key columns contain duplicate information. It allows us to keep instances of duplicates, using the keep parameter. With the keep parameter, we can specify whether we want to keep the “first” or “last” instance or drop all instances of the duplicate information. By default, the method keeps the first instance.

In [36]:
df3 = pd.read_csv("data/marketing_campaign.csv")
df3 = df3[['Education','Marital_Status','Kidhome', 'Teenhome']]
df3.head(5)

    Education Marital_Status  Kidhome  Teenhome
0  Graduation         Single        0         0
1  Graduation         Single        1         1
2  Graduation       Together        0         0
3  Graduation       Together        1         0
4         PhD        Married        1         0

In [39]:
df3.shape

(2240, 4)

In [40]:
df3_drop_duplicates = df3.drop_duplicates()
df3_drop_duplicates.shape

(135, 4)

In [41]:
df3_drop_duplicates.head(5)

    Education Marital_Status  Kidhome  Teenhome
0  Graduation         Single        0         0
1  Graduation         Single        1         1
2  Graduation       Together        0         0
3  Graduation       Together        1         0
4         PhD        Married        1         0

# Dropping data rows and columns
Sometimes, we may need to drop columns or rows either because they are erroneous or irrelevant.

In [42]:
df.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth,bins
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7,Low
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5,Low
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4,High
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6,Low
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5,Moderate

In [45]:
# Delete row at index 1, specify axis=0 for row
df4 = df.drop(labels=[1],axis=0)
df4.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth,bins
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7,Low
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4,High
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6,Low
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5,Moderate
5,7446,1967,Master,Together,62513.0,0,1,09-09-2013,16,10,6,High

In [46]:
# Delete a column: specify axis=1 for column
df5 = df4.drop(labels=["Year_Birth"],axis=1)
df5.head(5)

,ID,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth,bins
0,5524,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7,Low
2,4141,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4,High
3,6182,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6,Low
4,5324,PhD,Married,58293.0,1,0,19-01-2014,94,6,5,Moderate
5,7446,Master,Together,62513.0,0,1,09-09-2013,16,10,6,High

# Replacing Data

In [48]:
df5 = df[['ID', 'Year_Birth', 'Kidhome', 'Teenhome']]
df5.head(5)

     ID  Year_Birth  Kidhome  Teenhome
0  5524        1957        0         0
1  2174        1954        1         1
2  4141        1965        0         0
3  6182        1984        1         0
4  5324        1981        1         0

In [50]:
# Replace Teenhome values 0, 1, 2 with "has no teen" and "has teen"
df5['Teenhome_Replaced'] = df5['Teenhome'].replace([0,1,2],['has no teen','has teen','has teen'])
df5.head(5)

/var/folders/j_/vhqwplgn0c90lw00mz6mlg880000gn/T/ipykernel_1669/1089438907.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5['Teenhome_Replaced'] = df5['Teenhome'].replace([0,1,2],['has no teen','has teen','has teen'])

     ID  Year_Birth  Kidhome  Teenhome Teenhome_Replaced
0  5524        1957        0         0       has no teen
1  2174        1954        1         1          has teen
2  4141        1965        0         0       has no teen
3  6182        1984        1         0       has no teen
4  5324        1981        1         0       has no teen

# Changing a data format

In [53]:
df.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth,bins
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7,Low
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5,Low
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4,High
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6,Low
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5,Moderate

In [56]:
# Fill NA values in 'Income' with 0
df['Income'] = df['Income'].fillna(0)

# Change data type of Income column from float to int
df['Income'] = df['Income'].astype(int)

# Inspect output
df['Income'].dtypes

dtype('int64')

In [61]:
# Check if any value in Income column is null
df['Income'].isnull().unique()

array([False])

# Handling Missing Values
Pandas represents missing values as `NaN`

In [66]:
# Check number of missing values in each column
df6 = pd.read_csv('data/marketing_campaign.csv')
df6.isnull().sum()

Unnamed: 0              0
ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [69]:
# 'any': drop rows that have missing values
df6 = df6.dropna(how="any")

In [68]:
df6.isnull().sum()

Unnamed: 0             0
ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
dtype: int64